northlynwebsite/models.py
#models.py

from northlynwebsite import db, login_manager
from werkzeug.security import generate_password_hash,check_password_hash
from flask_login import UserMixin
from datetime import datetime

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(user_id)

class User(db.Model,UserMixin):

    __tablename__ = 'users'
    id = db.Column(db.Integer,primary_key=True)
    profile_image = db.Column(db.String(20),nullable=False,default='default_profile.png')
    email = db.Column(db.String(64),unique=True,index=True)
    username = db.Column(db.String(64),unique=True,index=True)
    password_hash = db.Column(db.String(128))

    posts = db.relationship('PagePost',backref='author',lazy=True)

    def __init__(self,email,username,password):
        self.email = email
        self.username = username
        self.password_hash = generate_password_hash(password)

    def check_password(self,password):
        return check_password_hash(self.password_hash,password)

    def repr(self):
        return f"Username: {self.username}"

class PagePost(db.Model):

    users = db.relationship(User)

    id = db.Column(db.Integer,primary_key=True)
    user_id = db.Column(db.Integer,db.ForeignKey('users.id'),nullable=False)

    date = db.Column(db.DateTime,nullable=False,default=datetime.utcnow)
    title = db.Column(db.String(140),nullable=False)
    text = db.Column(db.Text,nullable=False)

    def __init__(self,title,text,user_id):
        self.title = title
        self.text = Text
        self.user_id = user_id

    def repr(self):
        return f"Post ID: {self.id} -- Date: {self.date} --- {self.title}"

northlynwebsite/users/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField
from wtforms.validators import DataRequired, Email, EqualTo
from wtforms import ValidationError
from flask_wtf.file import FileField,FileAllowed

from flask_login import current_user
from northlynwebsite.models import User

class LoginForm(FlaskForm):
    email = StringField('Email',validators=[DataRequired(),Email()])
    password = PasswordField('Password',validators=[DataRequired()])
    submit = SubmitField('Log in')

class RegistrationForm(FlaskForm):
    email = StringField('Email-address',validators=[DataRequired(),Email()])
    username = StringField('Username',validators=[DataRequired()])
    password = PasswordField('Password',validators=[DataRequired(),EqualTo('pass_confirm',message='Passwords must match!')])
    pass_confirm = PasswordField('Confirm password',validators=[DataRequired()])
    submit = SubmitField('Register')

    def check_email(self,field):
        if User.query.filter_by(email=field.data).first():
            raise ValidationError('Your email has been registered already.')

    def check_username(self,field):
        if User.query.filter_by(username=field.data).first():
            raise ValidationError('Your username has been registered already.')

class UpdateUserForm(FlaskForm):
    email = StringField('Email',validators=[DataRequired(),Email()])
    username = StringField('Username',validators=[DataRequired()])
    picture = FileField('Update profile picture',validators=[FileAllowed(['jpg','png'])])
    submit = SubmitField('Update')

    def check_email(self,field):
        if User.query.filter_by(email=field.data).first():
            raise ValidationError('Your email has been registered already.')

    def check_username(self,field):
        if User.query.filter_by(username=field.data).first():
            raise ValidationError('Your username has been registered already.')

northlynwebsite/__init__.py
# northlynwebsite/__init__.py
import os, re
uri = os.getenv("DATABASE_URL")  # or other relevant config var
if uri.startswith("postgres://"):
   uri = uri.replace("postgres://", "postgresql://", 1)
# rest of connection code using the connection string `uri`

from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_login import LoginManager

app = Flask(__name__)

app.config['SECRET_KEY'] = os.getenv("SECRET_KEY")

### Database setup #####
#basedir = os.path.abspath(os.path.dirname(__file__))
#app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///' + os.path.join(basedir,'data.sqlite')
#app.config['SQLALCHEMY_DATABASE_URI'] = 'postgresql://postgres:postgres@localhost:5432/northlyn'
app.config['SQLALCHEMY_DATABASE_URI'] = uri

app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False

db = SQLAlchemy(app)
Migrate(app,db)

#### Login CONFIGURATIONS #####

login_manager = LoginManager()
login_manager.init_app(app)
login_manager.login_view = 'users.login'

######### blueprints ##########

from northlynwebsite.core.views import core
from northlynwebsite.users.views import users
from northlynwebsite.error_pages.handlers import error_pages
from northlynwebsite.char.views import char
app.register_blueprint(core)
app.register_blueprint(users)
app.register_blueprint(error_pages)
app.register_blueprint(char)

northlynwebsite/char/views.py
# char/views.py
from flask import render_template,request,Blueprint

char = Blueprint('char',__name__)

@char.route('/rotmus')
def rotmus():
    return render_template('rotmus.html')

@char.route('/doc')
def doc():
    return render_template('doc.html')

@char.route('/game')
def game():
    return render_template('game.html')

northlynwebsite/core/views.py
# core/views.py
from flask import render_template,request,Blueprint

core = Blueprint('core',__name__)

@core.route('/')
def index():
    return render_template('index.html')

@core.route('/info')
def info():
    return render_template('info.html')

northlynwebsite/users/views.py
#users.views.py
from flask import render_template,url_for,flash,redirect,request,Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from northlynwebsite import db
from northlynwebsite.models import User, PagePost
from northlynwebsite.users.forms import LoginForm, RegistrationForm, UpdateUserForm
from northlynwebsite.users.picture_handler import add_profile_pic

users = Blueprint('users',__name__)

#register
@users.route('/register',methods=['GET','POST'])
def register():
    form = RegistrationForm()
    if form.validate_on_submit():
        user = User(email=form.email.data,
                    username=form.username.data,
                    password=form.password.data)

        db.session.add(user)
        db.session.commit()
        flash('Thanks for registering')
        redirect(url_for('users.login'))
    return render_template('register.html',form=form)

#login
@users.route("/login",methods=['GET','POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user.check_password(form.password.data) and user is not None:
            login_user(user)
            flash('You have sucessfully logged in!')

            next = request.args.get('next')
            if next == None or not next[0] == '/':
                next = url_for('core.index')
            redirect(next)
    return render_template('login.html',form=form)


#logout
@users.route('/logout')
def logout():
    logout_user()
    return redirect(url_for("core.index"))

#account(update userform)
@users.route('/account',methods=['GET','POST'])
@login_required
def account():
    form = UpdateUserForm()
    if form.validate_on_submit():
        if form.picture.data:
            username = current_user.username
            pic = add_profile_pic(form.picture.data,username)
            current_user.profile_image = pic

        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('User account updated!')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email

    profile_image = url_for('static',filename='profile_pics/' + current_user.profile_image)
    return render_template('account.html',profile_image=profile_image,form=form)

#user's list of blog posts
@users.route("/<username>")
def user_posts(username):
    page = request.args.get('page',1,type=int)
    user = User.query.filter_by(username=username).first_or_404()
    page_posts = PagePost.query.filter_by(author=user).order_by(PagePost.date.desc()).paginate(page=page,per_page=5)
    return render_template('user_page_posts.html',page_posts=page_posts,user=user)

northlynwebsite/templates/account.html
{% extends "base.html" %}
{% block content %}
<div class="text-center" style="background-color: #9A616D;">
  <div class="col-lg-6 mx-auto">

    <section class="vh-120" style="background-color: #9A616D;">
      <div class="container py-5 h-120">
        <div class="row d-flex justify-content-center align-items-center h-120">
          <div class="col col-xl-10">
            <div class="card" style="border-radius: 1rem;">
              <div class="row g-0">
                <div class="col-md-6 col-lg-5 d-none d-md-block">
                  <img
                    src="{{url_for("static",filename='profile_pics/' + current_user.profile_image)}}"
                    alt="login form"
                    class="img-fluid" style="border-radius: 1rem 0 0 1rem;"
                  />
                </div>
                <div class="col-md-6 col-lg-7 d-flex align-items-center">
                  <div class="card-body p-4 p-lg-5 text-black">

                    <form method="POST" action="" enctype="multipart/form-data">

                      <div class="d-flex align-items-center mb-3 pb-1">
                        <span class="h1 fw-bold mb-0">Welcome to the page for {{current_user.username}}</span>
                      </div>

                      <h5 class="fw-normal mb-3 pb-3" style="letter-spacing: 1px;">Change account details</h5>
                      {{form.hidden_tag()}}
                      <div class="form-outline mb-4">
                      {{form.email.label(class="form-label")}} {{form.email(class="form-control form-control-lg")}}
                      </div>
                      <div class="form-outline mb-4">
                      {{form.username.label}} {{form.username(class="form-control form-control-lg")}}
                      </div>
                      <div class="form-outline mb-4">
                      {{form.picture.label(class="form-label")}}  {{form.picture(class="form-control")}}
                      </div>
                      <div class="pt-1 mb-4">
                      {{form.submit(class="btn btn-dark btn-lg btn-block")}}
                      </div>

                      <a href="#!" class="small text-muted">Terms of use.</a>
                      <a href="#!" class="small text-muted">Privacy policy</a>
                    </form>

                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>

  </div>
</div>
{% endblock %}

northlynwebsite/templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">


    <link rel="stylesheet" href="{{url_for('static', filename='mystyle.css')}}">

  </head>
  <body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand fw-bold" href="{{url_for('core.index')}}">Northlyn Isles</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              The World
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li><a class="dropdown-item" href="#">Cacti</a></li>
              <li><a class="dropdown-item" href="#">Narda</a></li>
              <li><a class="dropdown-item" href="#">Sunvault</a></li>
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item" href="#">Something else here</a></li>
            </ul>
          </li>

          <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
          <ul class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li class="dropdown-submenu"><a class="dropdown-item dropdown-toggle" href="#">Submenu wider text</a>
              <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="#">Submenu</a></li>
                <li><a class="dropdown-item" href="#">Submenu0</a></li>
                <li class="dropdown-submenu"><a class="dropdown-item dropdown-toggle" href="#">Submenu 1</a>
                  <ul class="dropdown-menu">
                    <li><a class="dropdown-item" href="#">Subsubmenu1</a></li>
                    <li><a class="dropdown-item" href="#">Subsubmenu1</a></li>
                  </ul>
                </li>
                <li class="dropdown-submenu"><a class="dropdown-item dropdown-toggle" href="#">Submenu 2</a>
                  <ul class="dropdown-menu">
                    <li><a class="dropdown-item" href="#">Subsubmenu2</a></li>
                    <li><a class="dropdown-item" href="#">Subsubmenu2</a></li>
                  </ul>
                </li>
              </ul>
            </li>
          </ul>
        </li>

          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Characters
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li><a class="dropdown-item" href="#">Doc</a></li>
              <li><a class="dropdown-item" href="{{url_for('char.rotmus')}}">Rotmus</a></li>
              <li><a class="dropdown-item" href="#">Game</a></li>
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item" href="#">Something else here</a></li>
            </ul>
          </li>
          {% if current_user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{{url_for('users.account')}}">Account</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{url_for('users.account')}}">Inventory</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{url_for('users.logout')}}">Log-out</a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{{url_for('users.login')}}">Login</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{url_for('users.register')}}">Register</a>
          </li>
          {% endif %}
          <li class="nav-item">
            <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
          </li>
        </ul>
        <form class="d-flex">
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
      </div>
    </div>
  </nav>

  <div>
  {% block content %}

  {% endblock %}
  </div>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj" crossorigin="anonymous"></script>
  </body>
</html>

northlynwebsite/templates/index.html
{% extends "base.html" %}
{% block content %}
<div class="bg-image d-flex justify-content-sm-center" style="background-image: url('{{url_for('static',filename="backgroundimage.jpg")}}');  background-attachment: fixed;">
  <div class=" text-center">
      <div class="card mx-auto col-lg-8 bg-dark" style="--bs-bg-opacity: .80;">
        <div class="card-body">
          <div class="container">
            <img class="d-block mx-auto img-fluid" src="{{url_for('static',filename="FFcrest.png")}}" alt="" width="350" height="auto">
            <h1 class="display-5 fw-bold fst-italic text-white py-5">Northlyn Isles</h1>
          </div>
          <iframe width="1000" height="515" src="https://www.youtube.com/embed/19dx6AkC_GY" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
          <div class="embed-responsive embed-responsive-16by9">
          <div class="text-white col-lg-10 mx-auto py-5">
            <p class="lead mb-4">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
            <div class="d-grid gap-2 d-sm-flex justify-content-sm-center">
              <button type="button" class="btn btn-primary btn-lg px-4 gap-3">Primary button</button>
              <button type="button" class="btn btn-outline-secondary btn-lg px-4">Secondary</button>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}

northlynwebsite/templates/login.html
{% extends "base.html" %}
{% block content %}
<div class="text-center" style="background-color: #9A616D;">
  <div class="col-lg-6 mx-auto">

    <section class="vh-120" style="background-color: #9A616D;">
      <div class="container py-5 h-120">
        <div class="row d-flex justify-content-center align-items-center h-120">
          <div class="col col-xl-10">
            <div class="card" style="border-radius: 1rem;">
              <div class="row g-0">
                <div class="col-md-6 col-lg-5 d-none d-md-block">
                  <img
                    src="https://images.pexels.com/photos/4588052/pexels-photo-4588052.jpeg?cs=srgb&dl=pexels-anna-shvets-4588052.jpg&fm=jpg"
                    alt="login form"
                    class="img-fluid" style="border-radius: 1rem 0 0 1rem;"
                  />
                </div>
                <div class="col-md-6 col-lg-7 d-flex align-items-center">
                  <div class="card-body p-4 p-lg-5 text-black">

                    <form method="POST">

                      <div class="d-flex align-items-center mb-3 pb-1">
                        <img
                          src="{{url_for('static',filename="d20.png")}}"
                          alt="login form"
                          class="img-fluid" style="border-radius: 1rem 0 0 1rem;"
                          width="60 "
                        />
                        <span class="h1 fw-bold mb-0">Login</span>
                      </div>

                      <h5 class="fw-normal mb-3 pb-3" style="letter-spacing: 1px;">Login to your account</h5>
                      {{form.hidden_tag()}}
                      <div class="form-outline mb-4">
                      {{form.email.label(class="form-label")}} {{form.email(class="form-control form-control-lg")}}
                      </div>
                      <div class="form-outline mb-4">
                      {{form.password.label}} {{form.password(class="form-control")}}
                      </div>
                      <div class="pt-1 mb-4">
                      {{form.submit(class="btn btn-dark btn-lg btn-block")}}
                      </div>

                      <a class="small text-muted" href="#!">Forgot password?</a>
                      <p class="mb-1 pb-lg-2" style="color: #393f81;">Don't have an account? <a href="{{url_for('users.register')}}" style="color: #393f81;">Register here</a></p>
                      <a href="#!" class="small text-muted">Terms of use.</a>
                      <a href="#!" class="small text-muted">Privacy policy</a>
                    </form>

                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>

  </div>
</div>
{% endblock %}

northlynwebsite/templates/register.html
{% extends "base.html" %}
{% block content %}
<div class="text-center" style="background-color: #9A616D;">
  <div class="col-lg-6 mx-auto">

    <section class="vh-120" style="background-color: #9A616D;">
      <div class="container py-5 h-120">
        <div class="row d-flex justify-content-center align-items-center h-120">
          <div class="col col-xl-10">
            <div class="card" style="border-radius: 1rem;">
              <div class="row g-0">
                <div class="col-md-6 col-lg-5 d-none d-md-block">
                  <img
                    src="https://images.pexels.com/photos/4588052/pexels-photo-4588052.jpeg?cs=srgb&dl=pexels-anna-shvets-4588052.jpg&fm=jpg"
                    alt="login form"
                    class="img-fluid" style="border-radius: 1rem 0 0 1rem;"
                  />
                </div>
                <div class="col-md-6 col-lg-7 d-flex align-items-center">
                  <div class="card-body p-4 p-lg-5 text-black">

                    <form method="POST">

                      <div class="d-flex align-items-center mb-3 pb-1">
                        <img
                          src="{{url_for('static',filename="d20.png")}}"
                          alt="login form"
                          class="img-fluid" style="border-radius: 1rem 0 0 1rem;"
                          width="60 "
                        />
                        <span class="h1 fw-bold mb-0">Register</span>
                      </div>

                      <h5 class="fw-normal mb-3 pb-3" style="letter-spacing: 1px;">Register an account</h5>
                      {{form.hidden_tag()}}
                      <div class="form-outline mb-4">
                      {{form.email.label(class="form-label")}} {{form.email(class="form-control form-control-lg")}}
                      </div>
                      <div class="form-outline mb-4">
                      {{form.username.label}} {{form.username(class="form-control form-control-lg")}}
                      </div>
                      <div class="form-outline mb-4">
                      {{form.password.label}} {{form.password(class="form-control")}}
                      </div>
                      <div class="form-outline mb-4">
                      {{form.pass_confirm.label}} {{form.pass_confirm(class="form-control")}}
                      </div>
                      <div class="pt-1 mb-4">
                      {{form.submit(class="btn btn-dark btn-lg btn-block")}}
                      </div>

                      <a href="#!" class="small text-muted">Terms of use.</a>
                      <a href="#!" class="small text-muted">Privacy policy</a>
                    </form>

                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>

  </div>
</div>
{% endblock %}

northlynwebsite/templates/rotmus.html
{% extends "base.html" %}
{% block content %}
<div class="bg-image bg-black d-flex justify-content-sm-center" style="background-image: url('{{url_for('static',filename="mountain.jpg")}}');  background-attachment: fixed;
            background-position: center;
            background-repeat: no-repeat;">
  <div class="text-center ">
      <div class="card mx-auto col-lg-8 bg-dark" style="--bs-bg-opacity: .80;">
        <div class="card-body">
          <div class="container">
            <img class="d-block mx-auto img-fluid" src="{{url_for('static',filename="zoltan.png")}}" alt="" width="200" height="auto">
            <h1 class="display-5 fw-bold fst-italic text-white pb-5">Rotmus</h1>
          </div>

          <div class="text-white col-lg-10 mx-auto">
            <p class="lead mb-4">Your attack roll is <b>1d20 + your ability modifier + your proficiency bonus</b> if you're proficient with the weapon you’re using.</p>
            <p class="lead mb-4">And for damage: When attacking with a weapon, you add your <b>ability modifier</b>(the same modifier used for the attack roll) and <b>rage bonus of +3</b> to the damage.</p>
            <p class="h5 mb-4">Attack Roll: 1d20 + ability modifier + proficiency bonus (+4)</p>
            <p class="h5 mb-4">Damage Roll: Damage + ability modifier + rage bonus (+3)</p>
          </div>
          <div class="text-white col-lg-10 mx-auto py-5">
            <h3 class="mb-4"><b>Rage</b></h3>
            <div class="text-start">
            <p class="lead mb-4">In battle, you fight with primal ferocity. On Your Turn, you can enter a rage as a Bonus Action.</p>
            <p class="lead mb-4">While raging, you gain the following benefits if you aren't wearing heavy armor:</p>
            <dl class="d-block mx-5">
              <dt class="">• You have advantage on Strength checks and Strength Saving Throws.</dt>
              <dt class="">• When you make a melee weapon Attack using Strength, you gain a +3 (at Lv 9) bonus to the damage roll. This bonus increases as you level.</dt>
              <dt class="">• You have Resistance to bludgeoning, piercing, and slashing damage.</dt>
            </dl>
            <p class="lead mb-4">If you are able to cast Spells, you can't cast them or concentrate on them while raging.</p>
            <p class="lead mb-4">Your rage lasts for 1 minute. It ends early if you are knocked Unconscious or if Your Turn ends and you haven't attacked a Hostile creature since your last turn or taken damage since then. You can also end your rage on Your Turn as a Bonus Action.</p>
            <p class="lead mb-4">Once you have raged the maximum number of times for your Barbarian level, you must finish a Long Rest before you can rage again. You may rage 2 times at 1st Level, 3 at 3rd, 4 at 6th, 5 at 12th, and 6 at 17th.</p>
            </div>
          </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}

northlynwebsite/templates/user_page_posts.html
{% extends "base.html" %}
{% block content %}
<div class="px-4 py-5 my-5 text-center">
  <img class="d-block mx-auto mb-4" src="{{url_for("static",filename='profile_pics/' + user.profile_image)}}" alt="" width="72" height="57">
  <h1 class="display-5 fw-bold">Welcome to the page for {{user.username}}</h1>
  <div class="col-lg-6 mx-auto">
    {% for post in page_posts.items %}
      <h2><a href="{{url_for('page_posts.page_post',page_post_id=post.id)}}">{{post.title}}</a></h2>
      Written by: <a href="{{url_for('users.users_post',username=post.author.username)}}">{{post.author.username}}></a>
      <p class="text-muted">Published on:{{post.date.strftime("%d/%m/%Y")}}</p>
      <br>
      <p>{{post.text}}</p>
      <br>
    {% endfor %}

    <nav aria-label="Page navigation example">
      <ul class="pagination">
        {% for page_num in page_posts.iter_pages(left_edge=1,right_edge=1,left_current=1,right_current=2) %}
          {% if page_posts.page == page_num %}
          <li class="page-item disabled"></li>
            <a class="page-link" href="{{url_for('users.user_posts',username=user.username,page=page_num)}}"></a>
          {% else %}
          <li class="page-item"></li>
            <a class="page-link" href="{{url_for('users.user_posts',username=user.username,page=page_num)}}"></a>
          {% endif %}
        {% end for %}
      </ul>
    </nav>

    <div class="d-grid gap-2 d-sm-flex justify-content-sm-center">
    </div>
  </div>
</div>
{% endblock %}